export const SET_ACCURATE = 'SET_ACCURATE';
export const SET_CUNNING = 'SET_CUNNING';
export const SET_DISCREET = 'SET_DISCREET';
export const SET_PERSUASIVE = 'SET_PERSUASIVE';
export const SET_QUICK = 'SET_QUICK';
export const SET_RESOLUTE = 'SET_RESOLUTE';
export const SET_STRONG = 'SET_STRONG';
export const SET_VIGILANT = 'SET_VIGILANT';

export const SET_CORRUPTION_THRESHOLD = 'SET_CORRUPTION_THRESHOLD';
export const SET_DEFENSE = 'SET_DEFENSE';
export const SET_PAIN_THRESHOLD = 'SET_PAIN_THRESHOLD';
export const SET_THOUGHNESS = 'SET_THOUGHNESS';

export const SET_CHARACTER_NAME = 'SET_CHARACTER_NAME';
export const SET_OCCUPATION = 'SET_OCCUPATION';
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const SET_QUOTE = 'SET_QUOTE';
export const SET_RACE = 'SET_RACE';
export const SET_SHADOW = 'SET_SHADOW';

export const SET_ABILITIES_OPTIONS = 'SET_ABILITIES_OPTIONS';
export const SET_RACES_OPTIONS = 'SET_RACES_OPTIONS';

export const INITIALIZE_CHARGEN = 'INITIALIZE_CHARGEN';
