export const REQUEST_DERIVED_ATTRIBUTES = 'REQUEST_DERIVED_ATTRIBUTES';

export const REQUEST_SUCCESS_DERIVED_ATTRIBUTES = 'REQUEST_SUCCESS_DERIVED_ATTRIBUTES';
export const REQUEST_FAILURE_DERIVED_ATTRIBUTES = 'REQUEST_FAILURE_DERIVED_ATTRIBUTES';
